### PR TITLE
1122 admin add intake

### PR DESCRIPTION
**Pull request by marcellmueller**
Implements #1122

### CODE REVIEW

**Review by rafasdc — COMMENTED** [review]
This is working great, only thing I noticed is that you create an intake where start date === end date: 
image

**Comment by marcellmueller** [comment]
> This is working great, only thing I noticed is that you can create an intake where start date === end date: image

I added a check in the database mutation that will throw if the start date is greater than or equal to the end date, as well as a pgtap test for it. Let me know if you can reproduce this on the front end again though! Thanks.

**Comment by rafasdc** [comment]
> 

The validation doesn't seem to trigger when there is an intake open, this is what I did: 

- Create a new intake that starts in 1 to 2 minutes
- Refresh the page once the new intake "starts"
- Create a future intake
- No validation

Result:

image

**Comment by marcellmueller** [comment]
> 

Screenshot 2023-08-01 at 10 58 34 AM

I can't reproduce this

**Comment by rafasdc** [comment]
> > 
> 
> Screenshot 2023-08-01 at 10 58 34 AM
> I can't reproduce this

I think this is probably fine the way it is, it is a very very edge case.

**Review by rafasdc — APPROVED** [review]

**Pull request merged**
