### PR TITLE
fix: no longer infinite loop on upload pages

### PR DESCRIPTION
**Pull request by AntBush**
https://app.zenhub.com/workspaces/ccbc---delivery-board-61c0c1204c8bcb001491c5f3/issues/bcgov/conn-ccbc-portal/708

Removes the internal state and useEffects to update the form

### CODE REVIEW

**Review by matthieu-foucault — COMMENTED** [review]
Should #655 be fixed in this PR too. Now that we don't have `useEffect`s , all of these `waitFor` in the test are probably not needed

**Comment by AntBush** [comment]
> Should #655 be fixed in this PR too. Now that we don't have `useEffect`s , all of these `waitFor` in the test are probably not needed

I hope so? It's hard to tell if the flakiness is fixed or if we just didn't hit the error

**Comment by matthieu-foucault** [comment]
> > Should #655 be fixed in this PR too. Now that we don't have `useEffect`s , all of these `waitFor` in the test are probably not needed
> 
> I hope so? It's hard to tell if the flakiness is fixed or if we just didn't hit the error

I meant, can you update to test to remove the `waitFor`s ? If the test works without `waitFor`s, it's less likely to be flaky

**Comment by AntBush** [comment]
> > > Should #655 be fixed in this PR too. Now that we don't have `useEffect`s , all of these `waitFor` in the test are probably not needed
> > 
> > 
> > I hope so? It's hard to tell if the flakiness is fixed or if we just didn't hit the error
> 
> I meant, can you update to test to remove the `waitFor`s ? If the test works without `waitFor`s, it's less likely to be flaky

Ah yeah that makes much more sense 😅

**Comment by AntBush** [comment]
https://github.com/bcgov/CONN-CCBC-portal/actions/runs/3137446447/jobs/5095649787#step:5:4162

Looks like it doesn't solve the flaky issue? The test is failing without the waitFors (unless I'm missing some piece of additional work that needs to be done)

**Review by matthieu-foucault — APPROVED** [review]

**Pull request merged**
