### PR TITLE
feat: enable real time color change

### PR DESCRIPTION
**Pull request by AntBush**
Implements NDT-227

### CODE REVIEW

**Comment by RRanath** [comment]
Looks Good😎 , but in the tickets it says `When user selects Null value the colour should change to white without having to refresh` which I guess we still have to address,

**Comment by AntBush** [comment]
> Looks Good😎 , but in the tickets it says `When user selects Null value the colour should change to white without having to refresh` which I guess we still have to address,

It should be blanking out the option now if you want to try it.

**Comment by RRanath** [comment]
@AntBush it seems to work for some statuses, not for some,
image

**Comment by AntBush** [comment]
@RRanath looks like I wasn't checking for when we were assigning the literal text "Unassigned", after copying over the test data it looks like it's working now.

**Review by RRanath — APPROVED** [review]
Approved

**Pull request merged**
