### PR TITLE
feat: add other files upload to funding agreement and change request

### PR DESCRIPTION
**Pull request by rafasdc**
Implements [NDT-266]

[NDT-266]: https://connectivitydivision.atlassian.net/browse/NDT-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by RRanath** [comment]
@rafasdc couple things I noticed,
- changes to this field results in error in history
image

- Do not remember if we decided to not show the listed files once collapsed(may be not important since they are `other files`)
image

**Comment by rafasdc** [comment]
> @rafasdc couple things I noticed,
> 
> * changes to this field results in error in history
>   image
> * Do not remember if we decided to not show the listed files once collapsed(may be not important since they are `other files`)
>   image

Great catches! Ready for second review whenever you have a chance :)

**Comment by RRanath** [comment]
Works Great!
Just noticed a small alignment issue
image

**Review by RRanath — APPROVED** [review]
Approved 🚀

**Pull request merged**
