### PR TITLE
Fix styled components rendering issues

### PR DESCRIPTION
**Pull request by BryanGK**
This PR is intended to fix the issues with styled-components not rendering properly on page loads

### CODE REVIEW

**Comment by wenzowski** [comment]
I notice we have the [chore: updates graphql schema](https://github.com/bcgov/CONN-CCBC-portal/pull/226/commits/05935ab321a9bfc1c82148b7e46a79d8e198ea55) bundled into this PR. Can we split out a PR for validating the graphql schema is in sync with the sqitch schema definitions + graphile plugins?

**Comment by BryanGK** [comment]
> I notice we have the [chore: updates graphql schema](https://github.com/bcgov/CONN-CCBC-portal/pull/226/commits/05935ab321a9bfc1c82148b7e46a79d8e198ea55) bundled into this PR. Can we split out a PR for validating the graphql schema is in sync with the sqitch schema definitions + graphile plugins?

Yeah I can do that but I seem have a knowledge gap as to why we would want to validate the graphql schema is in sync with the sqitch schema definitions + graphile plugins and why it can't be included in this PR.

**Comment by wenzowski** [comment]
> why it can't be included in this PR
No concerns with it being in this PR; part of the peer review process is identifying opportunities for improvement. A guardrail would ensure we end up having changes merged as logic units: clearly the chore done here was missed when the schema was last updated.

**Review by wenzowski — APPROVED** [review]
Looks great! Divergence between this and [bcgov/cas-cif#97](https://github.com/bcgov/cas-cif/pull/97/files) due to constraints introduced in newer version of Next.js

**Comment by wenzowski** [comment]
Manually tested & looking great

**Pull request merged**
